const fs = require('fs');
const path = require('path');

try {
  const rawCookies = fs.readFileSync(path.join(__dirname, 'raw-cookies.txt'), 'utf-8').trim();
  
  if (!rawCookies) {
    console.error('File raw-cookies.txt đang trống!');
    process.exit(1);
  }

  const cookiePairs = rawCookies.split(';');
  let netscapeFormat = "# Netscape HTTP Cookie File\n# Generated by convert-cookies.js\n\n";
  
  // Thời gian sống giả định (1 năm sau)
  const expireTime = Math.floor(Date.now() / 1000) + (365 * 24 * 60 * 60);

  for (let pair of cookiePairs) {
    pair = pair.trim();
    if (!pair) continue;
    
    const splitIndex = pair.indexOf('=');
    if (splitIndex === -1) continue;
    
    const name = pair.substring(0, splitIndex).trim();
    const value = pair.substring(splitIndex + 1).trim();
    
    // Domain \t IncludeSubdomains \t Path \t Secure \t Expiry \t Name \t Value
    // Với YouTube cookie, đa số có secure = TRUE, domain = .youtube.com
    const secure = name.startsWith('__Secure-') ? 'TRUE' : 'FALSE';
    
    netscapeFormat += `.youtube.com\tTRUE\t/\t${secure}\t${expireTime}\t${name}\t${value}\n`;
  }

  fs.writeFileSync(path.join(__dirname, 'cookies.txt'), netscapeFormat);
  console.log('✅ Đã chuyển đổi thành công sang cookies.txt chuẩn!');
} catch (err) {
  console.error('Lỗi:', err.message);
}
